"""add_task_collaboration_and_notification_models

Revision ID: 2a958ecc10db
Revises: 100c41b54576
Create Date: 2026-01-21 14:35:27.879048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a958ecc10db'
down_revision: Union[str, None] = '100c41b54576'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_created_by_id'), 'tasks', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_created_by_id'), table_name='tasks')
    op.drop_column('tasks', 'created_by_id')
    # ### end Alembic commands ###
