"""UpdateTableAttachment

Revision ID: 6e94355ffa11
Revises: 2a958ecc10db
Create Date: 2026-01-21 14:44:26.483580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e94355ffa11'
down_revision: Union[str, None] = '2a958ecc10db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
